### ISSUE TITLE
more json coordinates 

### ISSUE THREAD

**Issue by flutter-painter** [caduandrade/vector_map_flutter#14]
Very interesting project, how about adding more coordinates from : https://github.com/simplewidgets/countries_world_map ?
In fact, how about having a dedicated dart package where we map the whole world that could then be used by all mapping packages ?

**Comment by caduandrade** [comment]
Hi @flutter-painter !

Thanks. Unfortunately, as I'm short on time, I haven't dedicated myself to this API for a while. I'm focusing on the others.

It is not within the scope of the API to provide maps ok? It is worth remembering that this API could be used for other purposes, such as shopping mall floor plans, for example. The focus is to read any GeoJSON and so each project should look for its own sources. There are many public sources for this.

Only the example that already has GeoJSON to make it easier. I would have to review this in the final version because I believe that the package being published with JSON increases its size unnecessarily.
